---
- hosts: all
  sudo: true
  vars:
    web_server: nginxphp
    servername: talkly.vb www.takly.vb 192.168.33.100
    timezone: Europe/Berlin
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - nginx
    - php5-fpm
    - mysql
    - composer
    - nodejs
    - ruby
    - phpcommon
    - app
