---
- name: Install nodejs
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: ["nodejs", "nodejs-legacy"]

- name: Install npm
  sudo: yes
  apt: pkg=npm state=latest

- name: Install npm package
  sudo: yes
  npm: name={{ item }} global=yes state=latest
  with_items: npm_packages